name: SurealmsHome
version: 1.0.3
main: me.sanenuyan.homeGUI.HomeGUI
api-version: 1.18
authors: [SaneNuyan]
description: A standalone home management plugin with GUI and custom YAML database and permission-based max homes.
softdepend: [PlaceholderAPI]

commands:
  home:
    description: Opens the Home management GUI or quickly teleports to a home.
    usage: /home [home_name]
  homerefresh:
    description: Reloads the HomeGUI configuration.
    usage: /homerefresh
    permission: homegui.reload
  sethome:
    description: Sets a new home at the current location.
    usage: /sethome <home_name>
  delhome:
    description: Deletes an existing home.
    usage: /delhome <home_name>

permissions:
  homegui.reload:
    description: Allows reloading the HomeGUI configuration.
    default: op
  homegui.sethome:
    description: Allows setting homes.
    default: true
  homegui.delhome:
    description: Allows deleting homes.
    default: true
